### ISSUE TITLE
Simulating Real World Speaker

### ISSUE THREAD

**Issue by Udbhav17** [Vidyut-Projects-2k22/Speaker-Distortion-Compensation#1]
Simulating a real world speaker on Simulink, which includes the mathematically added real-world distortion of the speaker.

**Comment by anushudupi** [comment]
## Simulating Real world speaker
simulating  speaker model in simulink  with  both linear and nonlinear limitations of electric, magnetic, mechanical properties such as resistance, coil inductance ,self inductance of coil, magnetic induction, elastic nature of diaphragm, magnetic force, reluctance force, displacement, velocity, acceleration of diaphragm, damping factor of coil etc.
### Model
![model](https://user-images.githubusercontent.com/85610551/150671949-61732b6a-9c15-4ed7-bec6-50b51ffec00a.JPG)
[model.pdf](https://github.com/Vidyut-Projects-2k22/Speaker-Distortion-Compensation/files/7920127/model.pdf)

### Waveform
![waveform](https://user-images.githubusercontent.com/85610551/150672383-6f949b51-ddb8-4a58-940e-0870273b9a90.png)

### Frequency Response
#### Linear
![frequency_linear](https://user-images.githubusercontent.com/85610551/150672478-d7849497-3612-4afb-b268-6020c500f00e.JPG)
#### Logarithmic
![frequency_logarithamic](https://user-images.githubusercontent.com/85610551/150672636-b157e556-654e-4c76-b54b-e18d35eb00a6.JPG)
**We got the distortion in sound while simulating real world speaker and
We found that noises are frequency harmonics of the input waves which are causing the distortion in sound**

### Reference
[reference.pdf](https://github.com/Vidyut-Projects-2k22/Speaker-Distortion-Compensation/files/7920449/reference.pdf)

**Comment by Udbhav17** [comment]
The simulink file of the above model has also been attached here: 
[model.zip](https://github.com/Vidyut-Projects-2k22/Speaker-Distortion-Compensation/files/7920616/model.zip)
